#
# Autogenerated by Thrift
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'tracing_types'

  module FinagleThrift
    CLIENT_SEND = %q"cs"

    CLIENT_RECV = %q"cr"

    SERVER_SEND = %q"ss"

    SERVER_RECV = %q"sr"

    SERVER_ADDR = %q"sa"

    CLIENT_ADDR = %q"ca"

end
