java_library(name='java',
  provides = artifact(
    org = 'com.twitter',
    name = 'finagle-http2-java',
    repo = artifactory,
  ),
  dependencies=[
    '3rdparty/jvm/io/netty:netty4-http2',
  ],
  sources=rglobs('*.java'),
)
