java_thrift_library(name='thrift-scala',
  sources=rglobs('*.thrift'),
  compiler='scrooge',
  language='scala',
  rpc_style='finagle',
)

java_thrift_library(name='thrift-java',
  sources=rglobs('*.thrift'),
  compiler='scrooge',
  language='java',
)
