junit_tests(
    sources = ["**/*.java"],
    compiler_option_sets = [],
    dependencies = [
        "3rdparty/jvm/junit",
        "3rdparty/jvm/org/mockito:mockito-all",
        "finagle/finagle-core/src/main",
        "finagle/finagle-mysql",
        "util/util-function",
    ],
)
