junit_tests(
    sources = rglobs("*.java"),
    compiler_option_sets = {},
    dependencies = [
        "3rdparty/jvm/junit",
        "3rdparty/jvm/org/mockito:mockito-all",
        "finagle/finagle-core/src/main/scala",
        "finagle/finagle-mysql",
        "util/util-function",
    ],
)
