junit_tests(
    sources = ["**/*.java"],
    compiler_option_sets = ["fatal_warnings"],
    dependencies = [
        "finagle/finagle-core",
        "finagle/finagle-mux",
        "util/util-core",
    ],
)
