maven_layout()

jar_library(name='finagle-zipkin',
  dependencies=[
    pants('finagle/finagle-zipkin/src/main/scala')
  ]
)

jar_library(name='tests',
  dependencies=[
    pants('finagle/finagle-zipkin/src/test/scala')
  ]
)
