maven_layout()

jar_library(name='finagle-zipkin',
  dependencies=[
    'finagle/finagle-zipkin/src/main/scala'
  ]
)

jar_library(name='tests',
  dependencies=[
    'finagle/finagle-zipkin/src/test/scala'
  ]
)
