target(
    dependencies = [
        "finagle/finagle-memcached/src/main/java",
        "finagle/finagle-memcached/src/main/scala",
    ],
)

test_suite(
    name = "tests",
    dependencies = [
        "finagle/finagle-memcached/src/test/java",
        "finagle/finagle-memcached/src/test/scala",
    ],
)
