maven_layout()

jar_library(name='finagle-memcached',
  dependencies=[
    'finagle/finagle-memcached/src/main/java',
    'finagle/finagle-memcached/src/main/scala'
  ]
)

jar_library(name='tests',
  dependencies=[
    'finagle/finagle-memcached/src/test/java',
    'finagle/finagle-memcached/src/test/scala'
  ]
)
