target(name='finagle-redis',
  dependencies=[
    'finagle/finagle-redis/src/main/scala'
  ]
)

target(name='tests',
  dependencies=[
    'finagle/finagle-redis/src/test/java',
    'finagle/finagle-redis/src/test/scala'
  ]
)
