target(
    dependencies = [
        "finagle/finagle-redis/src/main/scala",
    ],
)

test_suite(
    name = "tests",
    dependencies = [
        "finagle/finagle-redis/src/test/scala",
    ],
)

test_suite(
    name = "integration-tests",
    dependencies = [
        "finagle/finagle-redis/src/it/scala",
    ],
)
