junit_tests(
    sources = rglobs("*.java"),
    compiler_option_sets = {"fatal_warnings"},
    dependencies = [
        "3rdparty/jvm/junit",
        "3rdparty/jvm/org/apache/thrift:libthrift",
        "finagle/finagle-core/src/main/scala",
        "finagle/finagle-mux/src/main/scala",
        "finagle/finagle-thrift/src/main/java",
        "finagle/finagle-thrift/src/main/scala",
        "finagle/finagle-thriftmux",
        "finagle/finagle-thriftmux/src/test/thrift:thrift-java",
        "finagle/finagle-thriftmux/src/test/thrift:thrift-scala",
        "scrooge/scrooge-core/src/main/scala",
        "util/util-core/src/main/java",
        "util/util-core/src/main/scala",
    ],
)
