/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.twitter.finagle.thrift.thrift;

import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class Constants {

  /**
   * The following is from BigBrotherBird:
   *   http://j.mp/fZZnyD
   */
  public static final String CLIENT_SEND = "cs";

  public static final String CLIENT_RECV = "cr";

  public static final String SERVER_SEND = "ss";

  public static final String SERVER_RECV = "sr";

  public static final String SERVER_ADDR = "sa";

  public static final String CLIENT_ADDR = "ca";

}
