target(
    dependencies = [
        "finagle/finagle-mysql/src/main/scala",
    ],
)

target(
    name = "tests",
    dependencies = [
        "finagle/finagle-mysql/src/test/java",
        "finagle/finagle-mysql/src/test/scala",
    ],
)
