maven_layout()

jar_library(name='finagle-mysql',
  dependencies=[
    pants('finagle/finagle-mysql/src/main/scala')
  ]
)

jar_library(name='tests',
  dependencies=[
    pants('finagle/finagle-mysql/src/test/scala')
  ]
)
