maven_layout()

jar_library(name='finagle-ostrich4',
  dependencies=[
    pants('finagle/finagle-ostrich4/src/main/scala')
  ]
)

jar_library(name='tests',
  dependencies=[
    pants('finagle/finagle-ostrich4/src/test/scala')
  ]
)
