maven_layout()

jar_library(name='finagle-ostrich4',
  dependencies=[
    'finagle/finagle-ostrich4/src/main/scala'
  ]
)

jar_library(name='tests',
  dependencies=[
    'finagle/finagle-ostrich4/src/test/scala'
  ]
)
