#!/bin/bash

function find_sbt_root {
  while [ ! -d project -a "x$PWD" != "x/" ] ; do
    cd ..
  done

  if [ "x$PWD" = "/" ]; then
    echo "couldn't find sbt project!" 1>&2
    exit 1
  fi

  echo $PWD
}

root=$(find_sbt_root)
if [ $? -ne 0 ]; then
  exit 1
fi

jars=$(echo $root/lib_managed/compile/*.jar $root/libs/*.jar | sed 's/ /:/g')

# To use YourKit:
#export JAVA_OPTS=-agentlib:yjpagent

if [ "$GCLOG" = "1" ]; then
  GC_OPTS="-verbosegc -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+PrintGCDateStamps -Xloggc:/tmp/gc.log"
fi

if [ "$PROFILE" = "1" ]; then
  JAVA_OPTS="-agentlib:yjpagent $JAVA_OPTS"
fi

if [ "$DEBUG" = "1" ]; then
  export JAVA_OPTS="-Xdebug -Xrunjdwp:transport=dt_socket,address=8000,server=y,suspend=n $JAVA_OPTS"

fi

export JAVA_OPTS="$JAVA_OPTS -server -Xmx2G -XX:MaxPermSize=256m -XX:+UseConcMarkSweepGC -XX:+UseParNewGC $GC_OPTS -Djava.net.preferIPv4Stack=true"
exec java $JAVA_OPTS -cp "$root/project/boot/scala-2.8.1/lib/scala-library.jar:$root/target/resources:$root/target/classes:$jars" "$@"
