maven_layout()

jar_library(name='finagle-serversets',
  dependencies=[
    'finagle/finagle-serversets/src/main/scala'
  ]
)

jar_library(name='tests',
  dependencies=[
    'finagle/finagle-serversets/src/test/scala'
  ]
)
