target(name='finagle-kestrel',
  dependencies=[
    'finagle/finagle-kestrel/src/main/java',
    'finagle/finagle-kestrel/src/main/scala'
  ]
)

target(name='tests',
  dependencies=[
    'finagle/finagle-kestrel/src/test/java',
    'finagle/finagle-kestrel/src/test/scala'
  ]
)
