maven_layout()

jar_library(name='finagle-kestrel',
  dependencies=[
    pants('finagle/finagle-kestrel/src/main/java'),
    pants('finagle/finagle-kestrel/src/main/scala')
  ]
)

jar_library(name='tests',
  dependencies=[
    pants('finagle/finagle-kestrel/src/test/java'),
    pants('finagle/finagle-kestrel/src/test/scala')
  ]
)
