package com.twitter.finagle.postgres.codec

import com.twitter.finagle.postgres.messages.PgRequest

/*
 * An error generated by Postgres.
 */
case class ServerError(
  message : String,
  request: Option[PgRequest],
  severity: Option[String],
  sqlState: Option[String] = None,
  detail: Option[String] = None,
  hint: Option[String] = None,
  position: Option[String] = None
) extends Exception(message)

/*
 * An error caused on the client side (e.g., a badly-formed query).
 */
case class ClientError(message : String) extends Exception(message)

object Errors {
  def client(message : String) = ClientError(message)
  def server(message : String,
             request: Option[PgRequest] = None,
             severity: Option[String] = None,
             sqlState: Option[String] = None,
             detail: Option[String] = None,
             hint: Option[String] = None,
             position: Option[String] = None) =
    ServerError(message, request, severity, sqlState, detail, hint, position)
}