package com.twitter.finagle.postgres.codec

import com.twitter.finagle.postgres.messages.PgRequest

/*
 * An error generated by Postgres.
 */
class ServerError(message : String, val request: Option[PgRequest], val severity: Option[String], val sqlState: Option[String] = None, val detail: Option[String] = None, val hint: Option[String] = None, val position: Option[String] = None) extends Exception(message)

/*
 * An error caused on the client side (e.g., a badly-formed query).
 */
class ClientError(message : String) extends Exception(message)

object Errors {
  def client(message : String) = new ClientError(message)
  def server(message : String,
             request: Option[PgRequest] = None,
             severity: Option[String] = None,
             sqlState: Option[String] = None,
             detail: Option[String] = None,
             hint: Option[String] = None,
             position: Option[String] = None) =
    new ServerError(message, request, severity, sqlState, detail, hint, position)
}