target(
    dependencies = [
        "finagle/finagle-netty4-http/src/main/scala",
    ],
)

target(
    name = "tests",
    dependencies = [
        "finagle/finagle-netty4-http/src/test/scala",
    ],
)
