#!/usr/bin/env bash

sbtver=1.3.10
sbtjar=sbt-launch.jar
sbtsha128=f49861befe36746728182ea7efb30096c724b0d7

sbtrepo="https://repo1.maven.org/maven2/org/scala-sbt/sbt-launch"

if [ ! -f $sbtjar ]; then
  echo "downloading $PWD/$sbtjar" 1>&2
  if ! curl --location --silent --fail --remote-name $sbtrepo/$sbtver/$sbtjar; then
    exit 1
  fi
fi

checksum=`openssl dgst -sha1 $sbtjar | awk '{ print $2 }'`
if [ "$checksum" != $sbtsha128 ]; then
  echo "bad $PWD/$sbtjar.  delete $PWD/$sbtjar and run $0 again."
  exit 1
fi

[ -f ~/.sbtconfig ] && . ~/.sbtconfig

# the -DSKIP_SBT flag is set to skip tests that shouldn't be run with sbt.
java -ea                          \
  $SBT_OPTS                       \
  $JAVA_OPTS                      \
  -DSKIP_SBT=1                    \
  -jar $sbtjar "$@"
