target(
    dependencies = [
        "finagle/finagle-zipkin-scribe/src/main/scala",
    ],
)

test_suite(
    name = "tests",
    dependencies = [
        "finagle/finagle-zipkin-scribe/src/test/scala",
    ],
)
