target(
    tags = ["bazel-compatible"],
    dependencies = [
        "finagle/finagle-zipkin-scribe/src/main/scala",
    ],
)

test_suite(
    name = "tests",
    tags = ["bazel-compatible"],
    dependencies = [
        "finagle/finagle-zipkin-scribe/src/test/scala",
    ],
)
