target(
    dependencies = [
        "finagle/finagle-zipkin-scribe/src/main/scala",
    ],
)

target(
    name = "core",
    dependencies = [
        "finagle/finagle-zipkin-scribe/src/main/scala:core",
    ],
)

target(
    name = "tests",
    dependencies = [
        "finagle/finagle-zipkin-scribe/src/test/scala",
    ],
)
