create_thrift_libraries(
  base_name='thrift',
  generate_languages=["java", "scala"],
  sources=rglobs('*.thrift'),
  provides_java_name='finagle-kestrel-thrift-java',
  provides_scala_name='finagle-kestrel-thrift-scala',
)
