junit_tests(
    sources = rglobs("*.scala"),
    fatal_warnings = True,
    dependencies = [
        "3rdparty/jvm/junit",
        "3rdparty/jvm/org/scalacheck",
        "3rdparty/jvm/org/scalatest",
        "finagle/finagle-toggle/src/main/scala/com/twitter/finagle/server",
        "finagle/finagle-tunable/src/main/scala",
        "finagle/finagle-tunable/src/test/resources",
        "util/util-tunable/src/main/scala",
    ],
)
