java_thrift_library(
    name = "thrift-scala",
    sources = ["**/*.thrift"],
    compiler = "scrooge",
    language = "scala",
)

java_thrift_library(
    name = "thrift-java",
    sources = ["**/*.thrift"],
    compiler = "scrooge",
    language = "java",
)
