junit_tests(
    sources = rglobs("*.java"),
    fatal_warnings = True,
    dependencies = [
        "3rdparty/jvm/io/netty",
        "3rdparty/jvm/junit",
        "finagle/finagle-base-http/src/main/scala",
        "finagle/finagle-core/src/main/java",
        "finagle/finagle-core/src/main/scala",
        "finagle/finagle-http",
        "finagle/finagle-http2",
        "util/util-core/src/main/java",
        "util/util-core/src/main/scala",
    ],
)
