junit_tests(
    sources = rglobs("*.java"),
    compiler_option_sets = {"fatal_warnings"},
    dependencies = [
        "3rdparty/jvm/junit",
        "finagle/finagle-base-http/src/main/scala",
        "finagle/finagle-core/src/main/java",
        "finagle/finagle-core/src/main/scala",
        "finagle/finagle-http",
        "finagle/finagle-http2",
        "util/util-core/src/main/java",
        "util/util-core/src/main/scala",
    ],
)
