maven_layout()

jar_library(name='finagle-stats',
  dependencies=[
    pants('finagle/finagle-stats/src/main/scala')
  ]
)

jar_library(name='tests',
  dependencies=[
    pants('finagle/finagle-stats/src/test/scala')
  ]
)
