maven_layout()

jar_library(name='finagle-stats',
  dependencies=[
    'finagle/finagle-stats/src/main/scala'
  ]
)

jar_library(name='tests',
  dependencies=[
    'finagle/finagle-stats/src/test/scala'
  ]
)
