target(
    dependencies = [
        "finagle/finagle-partitioning/src/main/scala",
    ],
)

test_suite(
    name = "tests",
    dependencies = [
        "finagle/finagle-partitioning/src/test/scala",
    ],
)
