target(
    dependencies = [
        "finagle/finagle-partitioning/src/main/scala",
    ],
)

target(
    name = "tests",
    dependencies = [
        "finagle/finagle-partitioning/src/test/scala",
    ],
)
