target(name='finagle-core',
  dependencies=[
    'finagle/finagle-core/src/main/java',
    'finagle/finagle-core/src/main/scala'
  ]
)

target(name='tests',
  dependencies=[
    'finagle/finagle-core/src/test/java',
    'finagle/finagle-core/src/test/scala'
  ]
)
