maven_layout()

jar_library(name='finagle-core',
  dependencies=[
    'finagle/finagle-core/src/main/scala'
  ]
)

jar_library(name='tests',
  dependencies=[
    'finagle/finagle-core/src/test/java',
    'finagle/finagle-core/src/test/scala'
  ]
)
