maven_layout()

jar_library(name='finagle-kestrelx',
  dependencies=[
    'finagle/finagle-kestrelx/src/main/java',
    'finagle/finagle-kestrelx/src/main/scala'
  ]
)

jar_library(name='tests',
  dependencies=[
    'finagle/finagle-kestrelx/src/test/java',
    'finagle/finagle-kestrelx/src/test/scala'
  ]
)
