scala_library(
    sources = ["**/*.scala"],
    compiler_option_sets = ["fatal_warnings"],
    platform = "java8",
    tags = ["bazel-compatible"],
    dependencies = [
        "finagle/finagle-core",
        "finagle/finagle-netty4",
        "util/util-core",
        "util/util-stats",
    ],
)
