java_thrift_library(name='thrift-scala',
  sources=rglobs('*.thrift'),
  compiler='scrooge',
  language='scala',
  rpc_style='finagle',
)

java_thrift_library(name='thrift-scala-legacy',
  sources=rglobs('*.thrift'),
  compiler='scrooge-legacy',
  language='scala',
  rpc_style='finagle',
)
