maven_layout()

jar_library(name='finagle-mdns',
  dependencies=[
    pants('finagle/finagle-mdns/src/main/scala')
  ]
)

jar_library(name='tests',
  dependencies=[
    pants('finagle/finagle-mdns/src/test/scala')
  ]
)
