maven_layout()

jar_library(name='finagle-mdns',
  dependencies=[
    'finagle/finagle-mdns/src/main/scala'
  ]
)

jar_library(name='tests',
  dependencies=[
    'finagle/finagle-mdns/src/test/scala'
  ]
)
