target(
  dependencies=[
    'finagle/finagle-mux/src/main/scala',
    'finagle/finagle-mux/src/main/java'
  ]
)

target(name='tests',
  dependencies=[
    'finagle/finagle-mux/src/test/java',
    'finagle/finagle-mux/src/test/scala'
  ]
)
