maven_layout()

jar_library(name='finagle-mux',
  dependencies=[
    'finagle/finagle-mux/src/main/scala'
  ]
)

jar_library(name='tests',
  dependencies=[
    'finagle/finagle-mux/src/test/java',
    'finagle/finagle-mux/src/test/scala'
  ]
)
