target(
    dependencies = [
        "finagle/finagle-mux/src/main/scala",
    ],
)

test_suite(
    name = "tests",
    dependencies = [
        "finagle/finagle-mux/src/test/java",
        "finagle/finagle-mux/src/test/scala",
    ],
)
