scala_library(
    compiler_option_sets = ["fatal_warnings"],
    tags = ["bazel-compatible"],
    dependencies = [
        "3rdparty/jvm/io/opencensus:opencensus-api",
        "finagle/finagle-core",
        "finagle/finagle-grpc-context/src/main/java/io/grpc/override",
        "finagle/finagle-http",
        "finagle/finagle-thriftmux",
    ],
)
