target(name='finagle-http2',
  dependencies=[
    'finagle/finagle-http2/src/main/scala',
    'finagle/finagle-http2/src/main/java',
  ]
)

target(name='tests',
  dependencies=[
    'finagle/finagle-http2/src/test/scala'
  ]
)
