create_thrift_libraries(
  base_name='thrift',
  jvm_only=True,
  sources=rglobs('*.thrift'),
  provides_java_name='finagle-kestrelx-thrift-java',
  provides_scala_name='finagle-kestrelx-thrift-scala',
)
