maven_layout()

jar_library(name='finagle-testers',
  dependencies=[
    'finagle/finagle-testers/src/main/scala'
  ]
)

jar_library(name='tests',
  dependencies=[
    'finagle/finagle-testers/src/test/scala'
  ]
)
