maven_layout()

jar_library(name='finagle-testers',
  dependencies=[
    pants('finagle/finagle-testers/src/main/scala')
  ]
)

jar_library(name='tests',
  dependencies=[
    pants('finagle/finagle-testers/src/test/scala')
  ]
)
