target(name='finagle-http-netty4',
  dependencies=[
    'finagle/finagle-http-netty4/src/main/scala'
  ]
)

target(name='tests',
  dependencies=[
    'finagle/finagle-http-netty4/src/test/scala'
  ]
)
