junit_tests(
    sources = rglobs("*.java"),
    fatal_warnings = True,
    dependencies = [
        "3rdparty/jvm/io/netty",
        "3rdparty/jvm/junit",
        "finagle/finagle-core",
        "util/util-core",
        "util/util-logging/src/main/scala",
        "util/util-stats/src/main/scala",
        "util/util-tunable/src/main/scala",
    ],
)
