junit_tests(
    sources = rglobs("*.java"),
    compiler_option_sets = {"fatal_warnings"},
    dependencies = [
        "3rdparty/jvm/junit",
        "finagle/finagle-core",
        "util/util-core",
        "util/util-logging/src/main/scala",
        "util/util-stats/src/main/scala",
        "util/util-tunable/src/main/scala",
    ],
)
