junit_tests(
    compiler_option_sets = {"fatal_warnings"},
    dependencies = [
        "3rdparty/jvm/io/grpc:grpc-context",
        "3rdparty/jvm/junit",
        "finagle/finagle-grpc-context/src/main/java/io/grpc/override",
        "util/util-core/src/main/scala/com/twitter/util",
    ],
)
