target(name='finagle-thriftmux',
  dependencies=[
    'finagle/finagle-thriftmux/src/main/scala'
  ]
)

target(name='tests',
  dependencies=[
    'finagle/finagle-thriftmux/src/test/java',
    'finagle/finagle-thriftmux/src/test/scala'
  ]
)
