junit_tests(
    sources = ["**/*.scala"],
    compiler_option_sets = ["fatal_warnings"],
    dependencies = [
        "3rdparty/jvm/junit",
        "3rdparty/jvm/org/apache/thrift:libthrift",
        "3rdparty/jvm/org/mockito:mockito-all",
        "3rdparty/jvm/org/scalacheck",
        "3rdparty/jvm/org/scalatest",
        "finagle/finagle-core/src/main",
        "finagle/finagle-thrift/src/main/java",
        "finagle/finagle-zipkin-core",
        "util/util-core:scala",
        "util/util-stats/src/main/scala",
    ],
)
