target(name='benchmark',
  dependencies=[
    'finagle/finagle-exp/src/main/scala:benchmark'
  ]
)

target(
  dependencies=[
    'finagle/finagle-exp/src/main/scala'
  ]
)

target(name='tests',
  dependencies=[
    'finagle/finagle-exp/src/test/scala'
  ]
)
