target(name='finagle-http-compat',
  dependencies=[
    'finagle/finagle-http-compat/src/main/scala'
  ]
)

target(name='tests',
  dependencies=[
    'finagle/finagle-http-compat/src/test/scala'
  ]
)
