maven_layout()

jar_library(name='finagle-exception',
  dependencies=[
    'finagle/finagle-exception/src/main/scala'
  ]
)

jar_library(name='tests',
  dependencies=[
    'finagle/finagle-exception/src/test/scala'
  ]
)
