target(
    dependencies = [
        "finagle/finagle-exception/src/main/scala",
    ],
)

test_suite(
    name = "tests",
    dependencies = [
        "finagle/finagle-exception/src/test/scala",
    ],
)
