maven_layout()

jar_library(name='finagle-exception',
  dependencies=[
    pants('finagle/finagle-exception/src/main/scala')
  ]
)

jar_library(name='tests',
  dependencies=[
    pants('finagle/finagle-exception/src/test/scala')
  ]
)
