maven_layout()

jar_library(name='finagle-httpx',
  dependencies=[
    'finagle/finagle-httpx/src/main/scala'
  ]
)

jar_library(name='tests',
  dependencies=[
    'finagle/finagle-httpx/src/test/java',
    'finagle/finagle-httpx/src/test/scala'
  ]
)
