maven_layout()

target(name='finagle-httpx',
  dependencies=[
    'finagle/finagle-httpx/src/main/scala',
    'finagle/finagle-httpx/src/main/java'
  ]
)

target(name='tests',
  dependencies=[
    'finagle/finagle-httpx/src/test/java',
    'finagle/finagle-httpx/src/test/scala'
  ]
)
