maven_layout()

target(name='finagle-httpx-compat',
  dependencies=[
    'finagle/finagle-httpx-compat/src/main/scala'
  ]
)

target(name='tests',
  dependencies=[
    'finagle/finagle-httpx-compat/src/test/scala'
  ]
)
