maven_layout()

jar_library(name='finagle-httpx-compat',
  dependencies=[
    'finagle/finagle-httpx-compat/src/main/scala'
  ]
)

jar_library(name='tests',
  dependencies=[
    'finagle/finagle-httpx-compat/src/test/scala'
  ]
)
