target(name='finagle-commons-stats',
  dependencies=[
    'finagle/finagle-commons-stats/src/main/scala'
  ]
)

target(name='tests',
  dependencies=[
    'finagle/finagle-commons-stats/src/test/scala'
  ]
)
