maven_layout()

jar_library(name='finagle-commons-stats',
  dependencies=[
    'finagle/finagle-commons-stats/src/main/scala'
  ]
)

jar_library(name='tests',
  dependencies=[
    'finagle/finagle-commons-stats/src/test/scala'
  ]
)
