maven_layout()

target(name='finagle-memcachedx',
  dependencies=[
    'finagle/finagle-memcachedx/src/main/java',
    'finagle/finagle-memcachedx/src/main/scala'
  ]
)

target(name='tests',
  dependencies=[
    'finagle/finagle-memcachedx/src/test/java',
    'finagle/finagle-memcachedx/src/test/scala'
  ]
)
