maven_layout()

jar_library(name='finagle-memcachedx',
  dependencies=[
    'finagle/finagle-memcachedx/src/main/java',
    'finagle/finagle-memcachedx/src/main/scala'
  ]
)

jar_library(name='tests',
  dependencies=[
    'finagle/finagle-memcachedx/src/test/java',
    'finagle/finagle-memcachedx/src/test/scala'
  ]
)
