java_library(name='java',
  provides = artifact(
    org = 'com.twitter',
    name = 'finagle-httpx-java',
    repo = artifactory,
  ),
  dependencies=[
    'finagle/finagle-httpx/src/main/scala'
  ],
  sources=rglobs('*.java'),
)
