maven_layout()

jar_library(name='finagle-thrift',
  dependencies=[
    'finagle/finagle-thrift/src/main/scala'
  ]
)

jar_library(name='tests',
  dependencies=[
    'finagle/finagle-thrift/src/test/java',
    'finagle/finagle-thrift/src/test/scala'
  ]
)
