target(name='finagle-zipkin-core',
  dependencies=[
    'finagle/finagle-zipkin-core/src/main/scala'
  ]
)

target(name='tests',
  dependencies=[
    'finagle/finagle-zipkin-core/src/test/scala'
  ]
)
