target(
    dependencies = [
        "finagle/finagle-zipkin-core/src/main/scala",
    ],
)

test_suite(
    name = "tests",
    dependencies = [
        "finagle/finagle-zipkin-core/src/test/scala",
    ],
)
