junit_tests(
    sources = rglobs("*.java"),
    compiler_option_sets = {"fatal_warnings"},
    dependencies = [
        "3rdparty/jvm/junit",
        "finagle/finagle-base-http/src/main/scala",
    ],
)
