target(
    name = "finagle-base-http",
    dependencies = [
        "finagle/finagle-base-http/src/main/scala",
    ],
)

target(
    name = "tests",
    dependencies = [
        "finagle/finagle-base-http/src/test/scala",
    ],
)
