target(
    name = "finagle-base-http",
    dependencies = [
        "finagle/finagle-base-http/src/main",
    ],
)

test_suite(
    name = "tests",
    dependencies = [
        "finagle/finagle-base-http/src/test/scala",
    ],
)
