maven_layout()

jar_library(name='finagle-spdy',
  dependencies=[
    'finagle/finagle-spdy/src/main/scala'
  ]
)

jar_library(name='tests',
  dependencies=[
    'finagle/finagle-spdy/src/test/scala'
  ]
)
