maven_layout()

target(name='finagle-http',
  dependencies=[
    'finagle/finagle-http/src/main/scala'
  ]
)

target(name='tests',
  dependencies=[
    'finagle/finagle-http/src/test/java',
    'finagle/finagle-http/src/test/scala'
  ]
)
