maven_layout()

jar_library(name='finagle-http',
  dependencies=[
    'finagle/finagle-http/src/main/scala'
  ]
)

jar_library(name='tests',
  dependencies=[
    'finagle/finagle-http/src/test/java',
    'finagle/finagle-http/src/test/scala'
  ]
)
